# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateTimeField(default=datetime.datetime(2017, 1, 11, 22, 35, 1, 419549))),
                ('parcelado', models.BooleanField(default=False)),
                ('n_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Número de Parcelas')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('icone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('pagamento', models.DateTimeField(blank=True, default=datetime.datetime(2017, 1, 11, 22, 35, 1, 420169), null=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Lancamento')),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Operacao'),
        ),
    ]
