# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='vencimento',
        ),
    ]
