# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_pessoa_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateTimeField(default=datetime.datetime(2016, 12, 26, 23, 20, 34, 848553))),
                ('parcelado', models.BooleanField(default=False)),
                ('n_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Número de Parcelas')),
                ('tipo', models.CharField(choices=[('e', 'Entrada'), ('s', 'Saída')], default='e', max_length=1)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa')),
            ],
        ),
    ]
