# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20170113_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
        ),
    ]
