# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('pagamento', models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 27, 0, 23, 29, 951205), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('cns', models.CharField(blank=True, max_length=15, null=True, verbose_name='CNS')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=50, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('cbo', models.IntegerField(blank=True, null=True, verbose_name='CBO')),
                ('n_conselho', models.IntegerField(blank=True, null=True, verbose_name='Conselho de Classe')),
                ('admissao', models.DateField(default=datetime.datetime(2016, 12, 27, 0, 23, 29, 949570))),
                ('ativo', models.BooleanField(default=False)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa')),
            ],
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default=0, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 0, 23, 29, 950568)),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Operacao'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Lancamento'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Endereco'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Pessoa'),
        ),
    ]
