# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20161227_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 30, 17, 56, 0, 569761)),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 30, 17, 56, 0, 570390), null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='admissao',
            field=models.DateField(default=datetime.datetime(2016, 12, 30, 17, 56, 0, 568777)),
        ),
    ]
