# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20170113_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Lancamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
